import { Button, Form, Input, Layout, Menu, Modal, Space, Table, Tag } from 'antd';
import { useEffect, useMemo, useState } from 'react';
import { api } from './api/client';
import { FieldSelect } from './components/FieldSelect';

const { Header, Sider, Content } = Layout;

function useFetch<T>(url: string) {
  const [data, setData] = useState<T[]>([]);
  const load = () => api.get(url).then((r) => setData(r.data));
  useEffect(() => { void load(); }, [url]);
  return { data, load };
}

const LoginPage = ({ onOk }: { onOk: () => void }) => <Layout style={{ minHeight: '100vh', placeItems: 'center', display: 'grid' }}><Form style={{ width: 320 }} onFinish={onOk}><Form.Item name="u" initialValue="admin"><Input placeholder="用户名"/></Form.Item><Form.Item><Button block type="primary" htmlType="submit">登录</Button></Form.Item></Form></Layout>;

function Dashboard() { return <div>欢迎使用金蝶精斗云库存替代决策中心。</div>; }
function Products() { const { data } = useFetch<any>('/products'); return <Table rowKey="id" dataSource={data} columns={[{title:'商品',render:(_,r)=>`${r.productName}/${r.productCode}`},{title:'仓库',dataIndex:'warehouseName'},{title:'单位',render:(_,r)=>`${r.baseUnit||'-'}/${r.auxUnit||'-'}`},{title:'换算',dataIndex:'conversionRate'},{title:'解析',render:(_,r)=>r.manualReviewRequired?<Tag color='red'>需人工复核</Tag>:<Tag color='green'>成功</Tag>},{title:'库存',dataIndex:'latestInventory'}]} />; }
function FieldMeta() { const { data, load } = useFetch<any>('/field-meta'); const [editing, setEditing]=useState<any>(); return <><Table rowKey="id" dataSource={data} columns={[{title:'来源',dataIndex:'source'},{title:'字段',render:(_,r)=>`${r.labelZh}（${r.fieldKey}）`},{title:'说明',dataIndex:'descriptionZh'},{title:'别名可编辑',render:(_,r)=>String(r.aliasEditable)},{title:'操作',render:(_,r)=><Button onClick={()=>setEditing(r)} disabled={!r.aliasEditable}>编辑别名</Button>}]} /><Modal open={!!editing} onCancel={()=>setEditing(undefined)} onOk={async()=>{await api.put(`/field-meta/${editing.id}`,{labelZh:editing.labelZh});setEditing(undefined);load();}}><Input value={editing?.labelZh} onChange={(e)=>setEditing({...editing,labelZh:e.target.value})}/></Modal></>; }

function Rules() { const { data, load } = useFetch<any>('/replacement-rules'); const products=useFetch<any>('/products/search?keyword=').data; const formulas=useFetch<any>('/formula-profiles').data; const [open,setOpen]=useState(false); const [form]=Form.useForm(); return <><Button type='primary' onClick={()=>setOpen(true)}>新增规则</Button><Table rowKey='ruleId' dataSource={data} columns={[{title:'源商品',render:(_,r)=>`${r.sourceProductName}/${r.sourceProductCode}`},{title:'替代商品',render:(_,r)=>`${r.targetProductName}/${r.targetProductCode}`},{title:'优先级',dataIndex:'priority'},{title:'启用',render:(_,r)=>String(r.enabled)}]} /><Modal open={open} onCancel={()=>setOpen(false)} onOk={async()=>{const v=await form.validateFields();await api.post('/replacement-rules',v);setOpen(false);load();}}><Form form={form} layout='vertical'><Form.Item name='sourceProductCode' label='原商品' rules={[{required:true}]}><Input list='p1'/></Form.Item><Form.Item name='targetProductCode' label='替代商品' rules={[{required:true}]}><Input list='p1'/></Form.Item><datalist id='p1'>{products.map((p:any)=><option key={p.id} value={p.productCode}>{`${p.productName}/${p.baseUnit||'-'}/${p.auxUnit||'-'}/${p.conversionRate||'-'}/${p.latestInventory||0}`}</option>)}</datalist><Form.Item name='sourceProductName' hidden><Input/></Form.Item><Form.Item name='targetProductName' hidden><Input/></Form.Item><Form.Item name='priority' initialValue={100}><Input/></Form.Item><Form.Item name='formulaProfileId' label='公式模板'><Input list='f1'/></Form.Item><datalist id='f1'>{formulas.map((f:any)=><option key={f.id} value={f.id}>{f.name}</option>)}</datalist></Form></Modal></>; }

function Formulas() { const { data, load } = useFetch<any>('/formula-profiles'); const fields=useFetch<any>('/field-meta').data.filter((f:any)=>f.source==='sales_order_detail'); const [open,setOpen]=useState(false); const [form]=Form.useForm(); return <><Button onClick={()=>setOpen(true)} type='primary'>新建公式模板</Button><Table rowKey='id' dataSource={data} columns={[{title:'名称',dataIndex:'name'},{title:'描述',dataIndex:'description'}]} /><Modal open={open} onCancel={()=>setOpen(false)} onOk={async()=>{const v=await form.validateFields();const configJson={demandFieldKey:v.demandFieldKey,executedFieldKey:v.executedFieldKey,purchaseInboundFieldKey:v.purchaseInboundFieldKey,purchaseTransitFieldKey:v.purchaseTransitFieldKey,salesOccupyFieldKey:v.salesOccupyFieldKey,instantInventoryFieldKey:v.instantInventoryFieldKey,compareUnit:v.compareUnit||'base_unit',threshold:Number(v.threshold||0)};await api.post('/formula-profiles',{name:v.name,description:v.description,configJson});setOpen(false);load();}}><Form form={form} layout='vertical'><Form.Item name='name' label='模板名称' rules={[{required:true}]}><Input/></Form.Item><Form.Item name='description' label='说明'><Input/></Form.Item><Form.Item name='demandFieldKey' label='需求字段'><FieldSelect fields={fields}/></Form.Item><Form.Item name='executedFieldKey' label='已执行字段'><FieldSelect fields={fields}/></Form.Item><Form.Item name='purchaseInboundFieldKey' label='采购订单入库字段'><FieldSelect fields={fields}/></Form.Item><Form.Item name='purchaseTransitFieldKey' label='采购在途字段'><FieldSelect fields={fields}/></Form.Item><Form.Item name='salesOccupyFieldKey' label='销售占用字段'><FieldSelect fields={fields}/></Form.Item><Form.Item name='instantInventoryFieldKey' label='即时库存字段' initialValue='instantqty'><FieldSelect fields={fields}/></Form.Item><Form.Item name='compareUnit' label='比较单位' initialValue='base_unit'><Input/></Form.Item><Form.Item name='threshold' label='阈值' initialValue={0}><Input/></Form.Item></Form></Modal></>; }

function Releases() { const { data, load } = useFetch<any>('/releases/history'); return <><Space><Button onClick={async()=>{await api.post('/releases/publish');load();}}>发布</Button></Space><Table rowKey='id' dataSource={data} columns={[{title:'版本',dataIndex:'version'},{title:'时间',dataIndex:'releasedAt'},{title:'状态',dataIndex:'status'},{title:'操作',render:(_,r)=><Button onClick={async()=>{await api.post(`/releases/${r.version}/rollback`);load();}}>回滚</Button>}]} /></>; }
function Audit() { const { data } = useFetch<any>('/audit-logs'); return <Table rowKey='id' dataSource={data} columns={[{title:'时间',dataIndex:'createdAt'},{title:'操作人',dataIndex:'actor'},{title:'动作',dataIndex:'action'},{title:'实体',render:(_,r)=>`${r.entityType}:${r.entityId}`}]} />; }

export default function App() {
  const [logged, setLogged] = useState(false);
  const [key, setKey] = useState('dashboard');
  const view = useMemo(() => ({ dashboard: <Dashboard />, products: <Products />, field: <FieldMeta />, rules: <Rules />, formulas: <Formulas />, releases: <Releases />, audit: <Audit /> }[key]), [key]);
  if (!logged) return <LoginPage onOk={() => setLogged(true)} />;
  return <Layout style={{ minHeight: '100vh' }}><Sider><Menu theme='dark' selectedKeys={[key]} onClick={(i)=>setKey(i.key)} items={[{key:'dashboard',label:'仪表盘'},{key:'products',label:'商品主数据'},{key:'field',label:'字段字典'},{key:'rules',label:'替代规则'},{key:'formulas',label:'公式模板'},{key:'releases',label:'发布管理'},{key:'audit',label:'审计日志'}]} /></Sider><Layout><Header style={{color:'#fff'}}>库存替代决策中心</Header><Content style={{padding:16}}>{view}</Content></Layout></Layout>;
}
